Fix Depth Outlines for URP 13+
Arvtesh/UnityFx.Outline pull request #62
Opened 2022-12-11 02:17 UTC by Casey-Hofland

Outlines would trigger a CommandBuffer warning (full error below) when "Enable Depth Testing" was enabled, turning the screen black.

For whatever reason, `new RenderTargetIdentifier("_CameraDepthTexture")` don't work no mo and Unity decided to provide no solid alternative (you could use camData.renderer.cameraDepthTargetHandle but it suffers from incompatibility with MSAA). THE ONLY FIX I could find was hidden in [some desolate forum](https://forum.unity.com/threads/how-to-set-_cameradepthtexture-as-render-target-in-urp-13.1279934/#post-8272821) using Reflection, thank god for the community.

Despite my attitude I'm really happy with this fix: this is the best Outline package out there (...right?) and I would hate for it to get abandoned because of Unity pullin' a fast one on us.

```
CommandBuffer: temporary render texture _CameraDepthTexture not found while executing Outline--1 (SetRenderTarget depth buffer)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

_sidenote: the diff is larger than it should be, probably because I updated line endings. Oh well 🤷_

2022-12-11 09:41 UTC, Arvtesh requested changes
Please add comments with a link to the workaround description on forums and it looks like indentation is messed up.

2022-12-11 13:06 UTC, Casey-Hofland commented
Weird, I don’t have any indentation issues on my system.
I assume you’re not talking about the directives aligned on the far left. My understanding is that that’s standard practice.

2023-01-13 11:58 UTC, Arvtesh approved these changes

2023-01-13 11:58 UTC, merged

2023-09-12 18:43 UTC, james-arndt-unity commented
This is still an issue. URP 14.0.8 using Unity 2022.3.6f1. Same exact error seen above when enabling "Enable Depth Testing".